export const CREATE_POST = "post/CREATE_POST"
export const FETCH_POSTS = "post/FETCH_POSTS"
export const SHOW_LOADER = "app/SHOW_LOADER"
export const HIDE_LOADER = "app/HIDE_LOADER"
export const SHOW_ALERT = "app/SHOW_ALERT"
export const HIDE_ALERT = "app/HIDE_ALERT"